theme: jekyll-theme-cayman

# Basic site configuration
title: Adaptly Documentation
description: AI-Adaptive UI Library for React & Next.js
author: Adaptly Team

# Disable Liquid processing completely
liquid:
  error_mode: ignore
  strict_filters: false
  strict_variables: false

# Disable Liquid processing for all markdown files
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      render_with_liquid: false

# Additional Liquid configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .gitignore
  - .git
  - .github
