remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

title: Adaptly Documentation
description: AI-Adaptive UI Library for React & Next.js

# Just the Docs theme configuration
search_enabled: true
search_tokenizer_separator: /[\s/]+/
search_placeholder: "Search docs..."
search_button_label: "Search"

# Navigation structure
nav:
  - title: Getting Started
    url: /
  - title: Quick Start
    url: quick-start.html
  - title: Component Registry
    url: component-registry.html
  - title: LLM Providers
    url: llm-providers.html
  - title: Storage Service
    url: storage-service.html
  - title: Advanced Features
    url: advanced-features.html
  - title: API Reference
    children:
      - title: Core Components
        url: api/core-components.html
      - title: Hooks
        url: api/hooks.html
      - title: Services
        url: api/services.html
      - title: Types
        url: api/types.html
  - title: Troubleshooting
    url: troubleshooting.html

# Header links
header_links:
  - title: "GitHub"
    url: "https://github.com/gauravfs-14/adaptly"

# Footer
footer_content: "Built with ❤️ by the Adaptly Team"

# Color scheme
color_scheme: light

# Markdown processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
  parse_block_html: true
  parse_span_html: true

# Disable Liquid processing for all markdown files
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      render_with_liquid: false

# SEO
author: Adaptly Team
twitter:
  username: adaptly_ui
  card: summary_large_image

# Social links
social:
  github: gauravfs-14/adaptly
  twitter: adaptly_ui

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .gitignore
  - .git
  - .github
