name: Publish NPM Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd adaptly-lib
          npm ci

      - name: Update package.json version from release tag
        run: |
          cd adaptly-lib
          # Get the release tag from GitHub release
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          VERSION=${RELEASE_TAG#v}

          # Update package.json version
          npm version $VERSION --no-git-tag-version

          # Commit the version change
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Update version to $VERSION for release $RELEASE_TAG"

          # Push the version update back to the main branch
          git push origin main

      - name: Build package
        run: |
          cd adaptly-lib
          npm run build

      - name: Run tests (if available)
        run: |
          cd adaptly-lib
          npm test || echo "No tests found, skipping..."
        continue-on-error: true

      - name: Publish to NPM
        run: |
          cd adaptly-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
