name: Publish NPM Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd adaptly-lib
          npm ci

      - name: Update package.json version from release tag
        run: |
          cd adaptly-lib
          # Get the release tag from GitHub release or use current tag
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            RELEASE_TAG="${{ github.event.release.tag_name }}"
            echo "Using release tag: $RELEASE_TAG"
          else
            # Fallback: get the latest tag from git
            RELEASE_TAG=$(git describe --tags --abbrev=0)
            echo "Using latest git tag: $RELEASE_TAG"
          fi

          # Extract version (remove 'v' prefix if present)
          VERSION=${RELEASE_TAG#v}
          echo "Version: $VERSION"

          # Validate version is not empty
          if [ -z "$VERSION" ]; then
            echo "Error: Version is empty. Release tag: $RELEASE_TAG"
            echo "Available tags:"
            git tag --list
            exit 1
          fi

          # Check if version needs updating
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          echo "Target version: $VERSION"

          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            echo "Updating version from $CURRENT_VERSION to $VERSION"
            npm version $VERSION --no-git-tag-version
          else
            echo "Version $VERSION is already set, skipping version update"
          fi

          # Only commit if there were changes
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            # Commit the version change
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add package.json
            git commit -m "Update version to $VERSION for release $RELEASE_TAG"

            # Push the version update back to the main branch
            # Create a new branch from the current commit and push it
            git checkout -b version-update-$VERSION
            git push origin version-update-$VERSION
          else
            echo "No version changes to commit"
          fi

      - name: Build package
        run: |
          cd adaptly-lib
          npm run build

      - name: Run tests (if available)
        run: |
          cd adaptly-lib
          npm test || echo "No tests found, skipping..."
        continue-on-error: true

      - name: Verify package can be published
        run: |
          cd adaptly-lib
          npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: |
          cd adaptly-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
